# Generated by Django 2.2.4 on 2019-08-18 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20190818_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
